const fs = require('fs');

/**
 * Generates a js file with an Array constant containing each
 * icon shape name from sketch files.
 *
 * Usage:
 * `node generateConstants '<src dir path>' '<dest dir path>'`
 */

const SRC_DIR = process.argv[2];
const DEST_DIR = process.argv[3];

const iconNames = fs.readdirSync(SRC_DIR)
	.filter(f => !f.includes('native'))    // files prefixed with `native` omit web artboards
	.map(f => f.replace('.sketch', ''));   // take the shape name only

const renderFileContent = iconNames => `/**
 * DO NOT EDIT DIRECTLY
 * --------------------
 * This file is generated by scripts/generateConstants.js
 * using icon file names.
 */
exports.VALID_SHAPES = [${iconNames.map(name => `'${name}'`)}];
`;

fs.writeFileSync(
	`${DEST_DIR}shapeConstants.js`,
	renderFileContent(iconNames)
);
